# Shadowrocket: 2026-04-30 12:15:18
[General]
bypass-system = true
loglevel = notify
ipv6 = false
udp = false
tcp-keep-alive = true
# 🔥 DoH прямо тут (не удаляется клиентом)
dns-server = system, 1.1.1.1, 8.8.8.8
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16

[Proxy]
Capybara = subscription, https://sub.capybara.support/Dn4wYaxxwd3tAe14

[Proxy Group]
# 🔥 Автовыбор лучшего сервера
Auto = url-test, Capybara, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50

# Ручной выбор
Proxy = select, Auto, YouTube, Telegram, DIRECT

[Rule]
# ❌ Убираем UDP полностью
AND,((PROTOCOL,UDP)),REJECT

# 🏠 Локальная сеть
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT

# 🔥 Исключение для капризных приложений
# Ozon + CDN
DOMAIN-SUFFIX,ozon.ru,DIRECT
DOMAIN-SUFFIX,ozoncdn.ru,DIRECT
DOMAIN-SUFFIX,ozone.ru,DIRECT
DOMAIN-KEYWORD,ozon,DIRECT
DOMAIN-KEYWORD,cdn,DIRECT
DOMAIN-KEYWORD,static,DIRECT

# 2Гис
DOMAIN-KEYWORD,gis,DIRECT
DOMAIN-SUFFIX,2gis.ru,DIRECT
DOMAIN-SUFFIX,2gis.com,DIRECT

# Т2
DOMAIN-SUFFIX,t2.ru,DIRECT
DOMAIN-SUFFIX,app-seller.ru,DIRECT
DOMAIN-KEYWORD,appseller,DIRECT
DOMAIN-KEYWORD,tele2,DIRECT

# 🇷🇺 Россия напрямую
GEOIP,RU,DIRECT,no-resolve
DOMAIN-SUFFIX,ru,DIRECT,no-resolve

# 🌍 Остальное
FINAL,PROXY

[Host]
localhost = 127.0.0.1